Implementacja metody w ScanningService
MikolajczukKamil/inwentaryzacja pull request #109
Opened 2020-05-05 16:47 UTC by RadoslawNagiel

2020-05-05 16:55 UTC, MikolajczukKamil reviewed
@Jerry-BloodBerry W pomieszczeniu przyda się nazwa budynku z którego pochodzi?
I przydało by się wstrzyknięcie `APIController` w konstruktorze

2020-05-05 19:53 UTC, Jerry-BloodBerry approved these changes
Myślę, że teraz jest ok 👍

2020-05-05 20:12 UTC, Jerry-BloodBerry requested changes
Ponieważ wszystkich o to proszę: 

- [ ] trzeba pousuwać przekazywanie przez referencję czyli słowo kluczowe ref z metod. Zostało ono automatycznie wygenerowane, a jest nam do niczego niepotrzebne

2020-05-06 16:56 UTC, Jerry-BloodBerry approved these changes
Myślę, że jest w porządku 👍  Jakiś konflikt się tu zrobił, trzeba będzie rozwiązać 😉

2020-05-12 17:23 UTC, closed without merging