Gogacz-ReportService
MikolajczukKamil/inwentaryzacja pull request #110
Opened 2020-05-05 19:30 UTC by StrongMen120

Gogacz-ReportService dodanie metod

2020-05-05 19:56 UTC, Jerry-BloodBerry approved these changes
Sprawdziłem, wszystko w porządku. Można mergować 👍 (Nieaktualne)

2020-05-05 20:00 UTC, Jerry-BloodBerry requested changes
Dlaczego room jest zmieniony z string na int a _reportPositions usunięte?

2020-05-05 20:04 UTC, MikolajczukKamil commented
`ref` jakie dodawał VP trzeba jeszcze wywalić, gdzieniegdzie się zapodziały te refy

2020-05-05 20:14 UTC, Jerry-BloodBerry commented
Trzeba też dodać konstruktor przyjmujący parametr typu APIController i ustawiający pole ApiController.

2020-05-06 16:53 UTC, Jerry-BloodBerry approved these changes
Wszystko okej, można mergować 👍

2020-05-06 16:53 UTC, merged