Logo i nazwa
MikolajczukKamil/inwentaryzacja pull request #214
Opened 2020-06-11 14:42 UTC by StrongMen120

Zmienione Logo
zmiana nazwy aplikacji

2020-06-11 16:16 UTC, Jerry-BloodBerry commented
Zmieniła się ikonka i nazwa, ale co z tym ekranem Xamarin? @MikolajczukKamil on ma tak zostać, czy jest inny pomysł na to?

2020-06-11 18:44 UTC, MikolajczukKamil commented
No właśnie chodzi o to aby zmienić również ekran powitalny, u mnie też coś jakby miga przewija się nie znikając na chwilę przed załadowaniem można zbadać o co chodzi
![Screenshot_2020-06-11-20-41-31-581_com companyname](https://user-images.githubusercontent.com/25321219/84426902-471b6800-ac24-11ea-8a95-84d6aa0e8877.jpg)

2020-06-11 20:50 UTC, MikolajczukKamil requested changes
zmienić ekran powitalny

2020-06-11 20:57 UTC, StrongMen120 commented
No dobra ale na co mam to zmienić ?

2020-06-12 09:16 UTC, MikolajczukKamil commented
> No dobra ale na co mam to zmienić ?

Logo
INWENTARYZACJA

po prostu :D

2020-06-12 19:52 UTC, MikolajczukKamil approved these changes

2020-06-12 19:52 UTC, MikolajczukKamil commented
Przy okazji dodałem kolorki

2020-06-12 19:52 UTC, merged