Maciej dominiak kalkulator
MikolajczukKamil/inwentaryzacja pull request #56
Opened 2020-03-30 19:54 UTC by maciek1651g

2020-04-01 09:21 UTC, ogrekpl commented
Jak byś dodał .gitignore dla Xamarina to by nie było prawie 2k plików razem ze skompilowanym projektem itp tylko same pliki .cs i inne istotne. Zwróć uwagę na to. Taka dobra rada na przyszłość ;)

2020-04-01 19:12 UTC, Jerry-BloodBerry requested changes
![obraz](https://user-images.githubusercontent.com/45820576/78176676-31880600-745d-11ea-8b6e-849f12fa1a8e.png)
Rozjeżdża się. Trzeba poprawić. Widzę, że wszędzie dałeś na sztywno wartości. Nie można tak, musi być relative, żeby na każdym urządzeniu był ładny widok. W tutorialu xamarina jest wyjaśnione jak to zrobić, żeby było ładnie.

2020-04-02 10:11 UTC, maciek1651g commented
Starałem się to poprawić jednak StackLayout się mnie nie słucha, możesz mi podesłać link z tym jak to zrobić poprawnie albo mogę to przepisać na siatkę(Grid) lub spróbować napisać to na RelativeLayout.

2020-04-02 12:02 UTC, Jerry-BloodBerry commented
Proponuję przepisać to na GridLayout. Nie będzie się wtedy na pewno rozjeżdżać. Link do filmu: https://www.youtube.com/watch?v=5XgxZBK6uPM

2020-04-02 14:35 UTC, maciek1651g commented
Powinno śmigać

2020-04-02 16:52 UTC, Jerry-BloodBerry approved these changes
Tak, teraz jest już w porządku. Zadanie zaliczone

2020-04-02 17:06 UTC, merged