Wdrazanie api
MikolajczukKamil/inwentaryzacja pull request #95
Opened 2020-04-24 17:48 UTC by maciek1651g

#90 
Do zmiany zostały jeszcze linki, na razie testowałem to na swojej stronie.
Oraz pojawił się problem, którego do końca nie umiem rozwiązać. Chodzi o dawanie znać użytkownikowi jeśli wystąpił jakiś błąd. Jest kilka błędów, które mogą wystąpić podczas wysyłania zapytania, stąd zwrócenie z funkcji false lub null nie do końca rozwiązuje sprawę. Roboczo użyłem zmiennej statycznej string 'message' żeby zapisać komentarz do ostatniego wykonania operacji na obiekcie, później można zamienić to na liczby oznaczające jakiś błąd. Ale nie podoba mi się takie rozwiązanie. Czekam na wasze opinie.

2020-04-24 21:23 UTC, MikolajczukKamil commented
Ogólnie jak wystąpił jakiś błąd z połączeniem np brak internetu to trzeba wycofać akcję np ładowanie raportu i wyświetlić komunikat np popupem i powrócić do np menu

2020-04-24 21:38 UTC, MikolajczukKamil commented
Widzę że zacząłeś już robić modele, jutro ustalimy kto ma jakimi modelami się zająć mam nadzieję że jakieś zostawiłeś innym :D , patrząc dalej działać to działa ale fajnie by było do tego podejść nieco bardziej profesjonalnie a w zasadzie po prostu porządnie.
Chodzi mi o zasady programowania obiektowego, nie mieszamy zadań tutaj np kod odpowiedzialny za komunikację z bazą danych jest rozsiany po wszystkich modelach, filozofia jest taka aby model (np Asset czy Building) nie wiedział skąd jest bo i po co mu taka informacja, może z bazy może z pliku a może zza krzaka :D zapisywaniami zajmują się serwisy one wiedzą skąd dany obiekt pochodzi i jak go stamtąd powołać do życia czy zapisać zmiany jakie się zdarzyły, model to model on się prezentuje na wybiegu robi co ma robić i tyle jest w jego obowiązkach, dalej problem z komunikacją błędów wynika bezpośrednio z tego podejścia jak requesty są rozsiane wszędzie to nikt nie poczuwa się do obowiązku komunikacji o błędach no bo właśnie kto ma do tego "uprawnienia", kolejny problem to ctrl c + ctrl v ten sam kod (kłania się zasada DRY) tu przydałby się APIController który przyjmie to na siebie i będzie robił requesty (tylko on) tu proponuję porobić mu metody odpowiadjące endpointom z bazy i wtedy każdy serwis sobie skorzysta z gotowej metody.

2020-04-24 21:41 UTC, MikolajczukKamil commented
Tak nieco widoku z góry, jest sobie model (co), serwisy (skąd i jak) a nad tym GUI czyli komunikacja z userem, i GUI sobie bierze dane z modelu i wyświetla to co potrzeba (nie modyfikuje), wszelakie akcje odsyła do modelu i po aktualizacji modelu aktualizuje siebie tylko patrząc co się zmieniło, jak użytkownik kliknie rozpocznij skanowanie to GUI nie otwiera czołgu i ogląda bebechy tylko wysyła do serwisu info chcę utworzyć nowy raport i reaguje na zmiany (obiekt jest samolubny i jak nie musi odsyła działania do innych)

2020-04-25 14:48 UTC, maciek1651g commented
#96 Myślę, że jestem krok dalej w zrozumieniu arkanów programowania obiektowego. Czekam na uwagi i komentarze.

2020-04-27 16:52 UTC, MikolajczukKamil requested changes
Ogólnie jest ok, ale dodam kilka uwag
- Lepiej będzie zrobić z tego zwykłą klasę, umożliwi to wstrzykiwanie zależności do serwisów
- Dobrze będzie zrobić mini konfiguracje np adres nie ustawiać na sztywno tylko raz w konfiguracji  ustawić
- Fajnie by było zwracać nie 2 zmienne prymitywne bo nie specjalnie wiadomo co to jest, tylko zrobić parsowanie jsona i zwracać gotowy obiekt który później serwisy sobie przerobią tu jest jeszcze kwestia sprawdzenia czy to co zostało zwrócone jest w dobrym formacie ale to zadanie bardziej dla serwisów
- Obsługa błędów, jest no proceduralna tzn zwracamy boola czy jest "done", można zrobić obsługę błędów na poważnie czyli jak jest błąd zwracamy null, a dodatkowo generujemy zdarzenie wystąpił błąd które odebrać będzie mógł odpowiedni serwis czy kontroller widoku i na to zareagować (daje to też plus taki że można dać status błędu np krytyczny - nie można się połączyć z bazą lub nie krytyczny np nie ma żądanej sali jak ktoś wpisze nie istniejącą salę)

2020-04-28 08:19 UTC, maciek1651g commented
- adres wyciągnąłem do zmiennej 
- gdy wystąpi błąd zwracany jest null lub false oraz wywoływany jest event(pierwszy raz robiłem takie coś, więc wymaga sprawdzenia czy tak to ma działać). 
- Jeśli chodzi o deserliazację JSON'a do obiektów, to potrzebowałbym modeli, więc albo czekamy na modele albo zwracamy JSON'a w stringu.

2020-04-28 18:53 UTC, MikolajczukKamil approved these changes
Jest dobrze, 
jako mini pierdółkę dodam że zamiast kopiować za każdym razem np `new Uri(url+"/asset/read.php");` można wykonać konkatenację raz w metodzie wykonującej końcowy request zwiększy to nieco czytelność i zmniejszy ilość miejsc podatnych na błędy, dodatkowo nie ma kopiowania - DRY

2020-04-28 18:53 UTC, merged